#!/usr/bin/python3
import sys
import Connect
import ConfigLoader
import View

view = View.View()
try:
    cl = ConfigLoader.ConfigLoader()
except Exception as e:
    print("Some errors occurred during parsing the config file")
    print(e)
    sys.exit(-1)

print(cl.get_conf_connection_attribute("ConnectionType"))
print(cl.ssh_config_file())
c = Connect.Connect(cl.ssh_config_file(), view)
print(c.getWindowsList())
