#!/usr/bin/python3
import sys
import Connect
import ConfigLoader
import View
import WindowManager
import time

view = View.View()

try:
    cl = ConfigLoader.ConfigLoader()
except Exception as e:
    print("Some errors occurred during parsing the config file")
    print(e)
    sys.exit(-1)

try:
    c = Connect.Connect(cl.ssh_config_file(), view)
except pxssh.ExceptionPxssh as err:
    view.send("pxssh error while connecting to server")
    view.send(err)
    sys.exit(-2)

wm = WindowManager.WindowManager(c, cl)

while True:
    request = view.promptAppRequest(wm.getWindowsList())
    if request == None: #If user asked to close
        sys.exit(0)

    view.send("Ask to open " + request['name'])
    port = wm.openVNCServer(request['id'])
    time.sleep(3)
    wm.openVNCClient(port)

