#!/usr/bin/python3
import sys
import Connect
import ConfigLoader
import View

view = View.View()
try:
    cl = ConfigLoader.ConfigLoader()
except Exception as e:
    print("Some errors occurred during parsing the config file")
    print(e)
    sys.exit(-1)

c = Connect.Connect(cl.ssh_config_file(), view)

while True:
    request = view.promptAppRequest(c.getWindowsList())
    if request == None: #If user asked to close
        sys.exit(0)

    view.send("Ask to open " + request['name'])

